apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradingmaster

resources:
  - namespace.yaml
  - postgres.yaml
  - kafka.yaml
  - fastapi.yaml
  - flink.yaml
  - prometheus.yaml
  - grafana.yaml
  - jaeger.yaml
  - loki.yaml
  - promtail.yaml