apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradingmaster

resources:
  - namespace.yaml
  - network-policy.yaml
  - postgres.yaml
  - kafka.yaml
  - db-migrate-job.yaml
  - fastapi.yaml
  - frontend.yaml
  - flink.yaml
  - eod-cronjob.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - grafana.yaml
  - jaeger.yaml
  - loki.yaml
  - promtail.yaml